### ISSUE TITLE
Switch from bcrypt to bcryptjs

### ISSUE THREAD

**Issue by kaustubhai** [codeuino/social-platform-donut-backend#202]
**Switching from bcrypt to bcryptjs**
Bcrypt demands a lot of dependancies while bcryptjs is a javascript only enhanced version of it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a fresh machine with no dependencies install
2. Try `npm install` on the cloned repo and bcrypt will give an error

**Console Log Output**
`node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-linux-x64.tar.gz`

**Comment by ksraj123** [comment]
A comprehensive list of dependencies required by `bcrypt` can be found [here](https://www.npmjs.com/package/bcrypt#dependencies) The backend code is ultimately meant to run on the server in a Linux environment where most of these dependencies are already present. The error you have mentioned is well document in `bcrypt`'s npm page itself [here](https://www.npmjs.com/package/bcrypt#install-via-npm). Please make sure that you have the required dependancies installed. Since bcrypt is written in C++ it has [better performance](https://medium.com/javascript-in-plain-english/node-js-bcrypt-vs-bcryptjs-benchmark-69a9e8254cc2) (faster) over `bcryptjs` written in JavaScript. Since the server side code is meant to run in Node.js only, not in the browser (where `brcryptjs` is used as an alternative to `bcrypt`) I think we would be better off tweaking our docker files and docs to ensure that we have all the dependencies.
